/*
 * Selling Partner API for Supply Sources
 * Manage configurations and capabilities of seller supply sources.
 *
 * OpenAPI spec version: 2020-07-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.amazon.SellingPartnerAPI.models;

import java.util.Objects;
import java.util.Arrays;
import com.amazon.SellingPartnerAPI.models.ParkingCostType;
import com.amazon.SellingPartnerAPI.models.ParkingSpotIdentificationType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * The parking configuration.
 */
@Schema(description = "The parking configuration.")


public class ParkingConfiguration {
  @SerializedName("parkingCostType")
  private ParkingCostType parkingCostType = null;

  @SerializedName("parkingSpotIdentificationType")
  private ParkingSpotIdentificationType parkingSpotIdentificationType = null;

  @SerializedName("numberOfParkingSpots")
  private Integer numberOfParkingSpots = null;

  public ParkingConfiguration parkingCostType(ParkingCostType parkingCostType) {
    this.parkingCostType = parkingCostType;
    return this;
  }

   /**
   * Get parkingCostType
   * @return parkingCostType
  **/
  @Schema(description = "")
  public ParkingCostType getParkingCostType() {
    return parkingCostType;
  }

  public void setParkingCostType(ParkingCostType parkingCostType) {
    this.parkingCostType = parkingCostType;
  }

  public ParkingConfiguration parkingSpotIdentificationType(ParkingSpotIdentificationType parkingSpotIdentificationType) {
    this.parkingSpotIdentificationType = parkingSpotIdentificationType;
    return this;
  }

   /**
   * Get parkingSpotIdentificationType
   * @return parkingSpotIdentificationType
  **/
  @Schema(description = "")
  public ParkingSpotIdentificationType getParkingSpotIdentificationType() {
    return parkingSpotIdentificationType;
  }

  public void setParkingSpotIdentificationType(ParkingSpotIdentificationType parkingSpotIdentificationType) {
    this.parkingSpotIdentificationType = parkingSpotIdentificationType;
  }

  public ParkingConfiguration numberOfParkingSpots(Integer numberOfParkingSpots) {
    this.numberOfParkingSpots = numberOfParkingSpots;
    return this;
  }

   /**
   * Get numberOfParkingSpots
   * @return numberOfParkingSpots
  **/
  @Schema(description = "")
  public Integer getNumberOfParkingSpots() {
    return numberOfParkingSpots;
  }

  public void setNumberOfParkingSpots(Integer numberOfParkingSpots) {
    this.numberOfParkingSpots = numberOfParkingSpots;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParkingConfiguration parkingConfiguration = (ParkingConfiguration) o;
    return Objects.equals(this.parkingCostType, parkingConfiguration.parkingCostType) &&
        Objects.equals(this.parkingSpotIdentificationType, parkingConfiguration.parkingSpotIdentificationType) &&
        Objects.equals(this.numberOfParkingSpots, parkingConfiguration.numberOfParkingSpots);
  }

  @Override
  public int hashCode() {
    return Objects.hash(parkingCostType, parkingSpotIdentificationType, numberOfParkingSpots);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParkingConfiguration {\n");
    
    sb.append("    parkingCostType: ").append(toIndentedString(parkingCostType)).append("\n");
    sb.append("    parkingSpotIdentificationType: ").append(toIndentedString(parkingSpotIdentificationType)).append("\n");
    sb.append("    numberOfParkingSpots: ").append(toIndentedString(numberOfParkingSpots)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
