/*
 * The Selling Partner API for FBA inbound operations.
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * OpenAPI spec version: 2024-03-20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.amazon.SellingPartnerAPI.models.fulfillment.inbound.v2024_03_20;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The page type to use to print the labels. Possible values: &#x27;A4_21&#x27;, &#x27;A4_24&#x27;, &#x27;A4_24_64x33&#x27;, &#x27;A4_24_66x35&#x27;, &#x27;A4_24_70x36&#x27;, &#x27;A4_24_70x37&#x27;, &#x27;A4_24i&#x27;, &#x27;A4_27&#x27;, &#x27;A4_40_52x29&#x27;, &#x27;A4_44_48x25&#x27;, &#x27;Letter_30&#x27;.
 */
@JsonAdapter(ItemLabelPageType.Adapter.class)
public enum ItemLabelPageType {
  @SerializedName("A4_21")
  A4_21("A4_21"),
  @SerializedName("A4_24")
  A4_24("A4_24"),
  @SerializedName("A4_24_64x33")
  A4_24_64X33("A4_24_64x33"),
  @SerializedName("A4_24_66x35")
  A4_24_66X35("A4_24_66x35"),
  @SerializedName("A4_24_70x36")
  A4_24_70X36("A4_24_70x36"),
  @SerializedName("A4_24_70x37")
  A4_24_70X37("A4_24_70x37"),
  @SerializedName("A4_24i")
  A4_24I("A4_24i"),
  @SerializedName("A4_27")
  A4_27("A4_27"),
  @SerializedName("A4_40_52x29")
  A4_40_52X29("A4_40_52x29"),
  @SerializedName("A4_44_48x25")
  A4_44_48X25("A4_44_48x25"),
  @SerializedName("Letter_30")
  LETTER_30("Letter_30");

  private String value;

  ItemLabelPageType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ItemLabelPageType fromValue(String input) {
    for (ItemLabelPageType b : ItemLabelPageType.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<ItemLabelPageType> {
    @Override
    public void write(final JsonWriter jsonWriter, final ItemLabelPageType enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public ItemLabelPageType read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return ItemLabelPageType.fromValue((String)(value));
    }
  }
}
