/*
 * Selling Partner API for Supply Sources
 * Manage configurations and capabilities of seller supply sources.
 *
 * OpenAPI spec version: 2020-07-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.amazon.SellingPartnerAPI.models.supplysources.v2020_07_01;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The parking cost type.
 */
@JsonAdapter(ParkingCostType.Adapter.class)
public enum ParkingCostType {
  @SerializedName("Free")
  FREE("Free"),
  @SerializedName("Other")
  OTHER("Other");

  private String value;

  ParkingCostType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ParkingCostType fromValue(String input) {
    for (ParkingCostType b : ParkingCostType.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<ParkingCostType> {
    @Override
    public void write(final JsonWriter jsonWriter, final ParkingCostType enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public ParkingCostType read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return ParkingCostType.fromValue((String)(value));
    }
  }
}
