/*
 * Fulfillment Inbound v2024-03-20
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * OpenAPI spec version: 2024-03-20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.amazon.SellingPartnerAPI;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The owner of the preparations, if special preparations are required.
 */
@JsonAdapter(PrepOwner.Adapter.class)
public enum PrepOwner {
  @SerializedName("AMAZON")
  AMAZON("AMAZON"),
  @SerializedName("SELLER")
  SELLER("SELLER"),
  @SerializedName("NONE")
  NONE("NONE");

  private String value;

  PrepOwner(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PrepOwner fromValue(String input) {
    for (PrepOwner b : PrepOwner.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<PrepOwner> {
    @Override
    public void write(final JsonWriter jsonWriter, final PrepOwner enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public PrepOwner read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return PrepOwner.fromValue((String)(value));
    }
  }
}
