/*
 * Selling Partner API for Replenishment
 * The Selling Partner API for Replenishment (Replenishment API) provides programmatic access to replenishment program metrics and offers. These programs provide recurring delivery of any replenishable item at a frequency chosen by the customer.  The Replenishment API is available worldwide wherever Amazon Subscribe & Save is available or is supported. The API is available to vendors and FBA selling partners.
 *
 * OpenAPI spec version: 2022-11-07
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.amazon.SellingPartnerAPI.models.replenishment.v2022_11_07;

import java.util.Objects;
import java.util.Arrays;
import com.amazon.SellingPartnerAPI.models.replenishment.v2022_11_07.ListOfferMetricsRequestFilters;
import com.amazon.SellingPartnerAPI.models.replenishment.v2022_11_07.ListOfferMetricsRequestPagination;
import com.amazon.SellingPartnerAPI.models.replenishment.v2022_11_07.ListOfferMetricsRequestSort;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * The request body for the &#x60;listOfferMetrics&#x60; operation.
 */
@Schema(description = "The request body for the `listOfferMetrics` operation.")


public class ListOfferMetricsRequest {
  @SerializedName("pagination")
  private ListOfferMetricsRequestPagination pagination = null;

  @SerializedName("sort")
  private ListOfferMetricsRequestSort sort = null;

  @SerializedName("filters")
  private ListOfferMetricsRequestFilters filters = null;

  public ListOfferMetricsRequest pagination(ListOfferMetricsRequestPagination pagination) {
    this.pagination = pagination;
    return this;
  }

   /**
   * Get pagination
   * @return pagination
  **/
  @Schema(required = true, description = "")
  public ListOfferMetricsRequestPagination getPagination() {
    return pagination;
  }

  public void setPagination(ListOfferMetricsRequestPagination pagination) {
    this.pagination = pagination;
  }

  public ListOfferMetricsRequest sort(ListOfferMetricsRequestSort sort) {
    this.sort = sort;
    return this;
  }

   /**
   * Get sort
   * @return sort
  **/
  @Schema(description = "")
  public ListOfferMetricsRequestSort getSort() {
    return sort;
  }

  public void setSort(ListOfferMetricsRequestSort sort) {
    this.sort = sort;
  }

  public ListOfferMetricsRequest filters(ListOfferMetricsRequestFilters filters) {
    this.filters = filters;
    return this;
  }

   /**
   * Get filters
   * @return filters
  **/
  @Schema(required = true, description = "")
  public ListOfferMetricsRequestFilters getFilters() {
    return filters;
  }

  public void setFilters(ListOfferMetricsRequestFilters filters) {
    this.filters = filters;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListOfferMetricsRequest listOfferMetricsRequest = (ListOfferMetricsRequest) o;
    return Objects.equals(this.pagination, listOfferMetricsRequest.pagination) &&
        Objects.equals(this.sort, listOfferMetricsRequest.sort) &&
        Objects.equals(this.filters, listOfferMetricsRequest.filters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pagination, sort, filters);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListOfferMetricsRequest {\n");
    
    sb.append("    pagination: ").append(toIndentedString(pagination)).append("\n");
    sb.append("    sort: ").append(toIndentedString(sort)).append("\n");
    sb.append("    filters: ").append(toIndentedString(filters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
