/*
 * The Selling Partner API for FBA inbound operations.
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * OpenAPI spec version: 2024-03-20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package software.amazon.spapi.models.fulfillment.inbound.v2024_03_20;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import software.amazon.spapi.models.fulfillment.inbound.v2024_03_20.UnitOfWeight;
/**
 * The range of weights that are allowed for a package.
 */
@Schema(description = "The range of weights that are allowed for a package.")


public class WeightRange {
  @SerializedName("maximum")
  private BigDecimal maximum = null;

  @SerializedName("minimum")
  private BigDecimal minimum = null;

  @SerializedName("unit")
  private UnitOfWeight unit = null;

  public WeightRange maximum(BigDecimal maximum) {
    this.maximum = maximum;
    return this;
  }

   /**
   * Maximum allowed weight.
   * minimum: 0
   * maximum: 100000
   * @return maximum
  **/
  @Schema(required = true, description = "Maximum allowed weight.")
  public BigDecimal getMaximum() {
    return maximum;
  }

  public void setMaximum(BigDecimal maximum) {
    this.maximum = maximum;
  }

  public WeightRange minimum(BigDecimal minimum) {
    this.minimum = minimum;
    return this;
  }

   /**
   * Minimum allowed weight.
   * minimum: 0
   * maximum: 100000
   * @return minimum
  **/
  @Schema(required = true, description = "Minimum allowed weight.")
  public BigDecimal getMinimum() {
    return minimum;
  }

  public void setMinimum(BigDecimal minimum) {
    this.minimum = minimum;
  }

  public WeightRange unit(UnitOfWeight unit) {
    this.unit = unit;
    return this;
  }

   /**
   * Get unit
   * @return unit
  **/
  @Schema(required = true, description = "")
  public UnitOfWeight getUnit() {
    return unit;
  }

  public void setUnit(UnitOfWeight unit) {
    this.unit = unit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WeightRange weightRange = (WeightRange) o;
    return Objects.equals(this.maximum, weightRange.maximum) &&
        Objects.equals(this.minimum, weightRange.minimum) &&
        Objects.equals(this.unit, weightRange.unit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maximum, minimum, unit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WeightRange {\n");
    
    sb.append("    maximum: ").append(toIndentedString(maximum)).append("\n");
    sb.append("    minimum: ").append(toIndentedString(minimum)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
