/*
 * Selling Partner API for Pricing
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer pricing information for Amazon Marketplace products.  For more information, refer to the [Product Pricing v2022-05-01 Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v2022-05-01-use-case-guide).
 *
 * OpenAPI spec version: 2022-05-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.amazon.SellingPartnerAPI.models.pricing.v2022_05_01;

import java.util.Objects;
import java.util.Arrays;
import com.amazon.SellingPartnerAPI.models.pricing.v2022_05_01.SegmentDetails;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Input segment for featured offer expected price. The segment contains the location information for which featured offer expected price is requested.
 */
@Schema(description = "Input segment for featured offer expected price. The segment contains the location information for which featured offer expected price is requested.")


public class Segment {
  @SerializedName("segmentDetails")
  private SegmentDetails segmentDetails = null;

  public Segment segmentDetails(SegmentDetails segmentDetails) {
    this.segmentDetails = segmentDetails;
    return this;
  }

   /**
   * Get segmentDetails
   * @return segmentDetails
  **/
  @Schema(description = "")
  public SegmentDetails getSegmentDetails() {
    return segmentDetails;
  }

  public void setSegmentDetails(SegmentDetails segmentDetails) {
    this.segmentDetails = segmentDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Segment segment = (Segment) o;
    return Objects.equals(this.segmentDetails, segment.segmentDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(segmentDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Segment {\n");
    
    sb.append("    segmentDetails: ").append(toIndentedString(segmentDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
