/*
 * The Selling Partner API for Amazon Warehousing and Distribution
 * The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory. 
 *
 * OpenAPI spec version: 2024-05-09
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.amazon.SellingPartnerAPI.models.awd;

import java.util.Objects;
import java.util.Arrays;
import com.amazon.SellingPartnerAPI.models.awd.DistributionPackageQuantity;
import com.amazon.SellingPartnerAPI.models.awd.OrderAttribute;
import com.amazon.SellingPartnerAPI.models.awd.ProductQuantity;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Payload for creating an outbound order.
 */
@Schema(description = "Payload for creating an outbound order.")


public class OutboundOrderCreationData {
  @SerializedName("orderPreferences")
  private List<OrderAttribute> orderPreferences = null;

  @SerializedName("packagesToOutbound")
  private List<DistributionPackageQuantity> packagesToOutbound = null;

  @SerializedName("productsToOutbound")
  private List<ProductQuantity> productsToOutbound = null;

  public OutboundOrderCreationData orderPreferences(List<OrderAttribute> orderPreferences) {
    this.orderPreferences = orderPreferences;
    return this;
  }

  public OutboundOrderCreationData addOrderPreferencesItem(OrderAttribute orderPreferencesItem) {
    if (this.orderPreferences == null) {
      this.orderPreferences = new ArrayList<OrderAttribute>();
    }
    this.orderPreferences.add(orderPreferencesItem);
    return this;
  }

   /**
   * Order preferences for the outbound order.
   * @return orderPreferences
  **/
  @Schema(example = "[{\"orderPreference\":\"PARTIAL_ORDER\",\"orderPreferenceValue\":\"SET\"}]", description = "Order preferences for the outbound order.")
  public List<OrderAttribute> getOrderPreferences() {
    return orderPreferences;
  }

  public void setOrderPreferences(List<OrderAttribute> orderPreferences) {
    this.orderPreferences = orderPreferences;
  }

  public OutboundOrderCreationData packagesToOutbound(List<DistributionPackageQuantity> packagesToOutbound) {
    this.packagesToOutbound = packagesToOutbound;
    return this;
  }

  public OutboundOrderCreationData addPackagesToOutboundItem(DistributionPackageQuantity packagesToOutboundItem) {
    if (this.packagesToOutbound == null) {
      this.packagesToOutbound = new ArrayList<DistributionPackageQuantity>();
    }
    this.packagesToOutbound.add(packagesToOutboundItem);
    return this;
  }

   /**
   * List of packages to be outbound.
   * @return packagesToOutbound
  **/
  @Schema(example = "[{\"count\":1,\"distributionPackage\":{\"contents\":{\"products\":[{\"quantity\":1,\"sku\":\"testPen\"}]},\"measurements\":{\"dimensions\":{\"height\":1,\"length\":1,\"unitOfMeasurement\":\"INCHES\",\"width\":1},\"volume\":{\"unitOfMeasurement\":\"CUIN\",\"volume\":1},\"weight\":{\"unitOfMeasurement\":\"POUNDS\",\"weight\":1}},\"type\":\"CASE\"}}]", description = "List of packages to be outbound.")
  public List<DistributionPackageQuantity> getPackagesToOutbound() {
    return packagesToOutbound;
  }

  public void setPackagesToOutbound(List<DistributionPackageQuantity> packagesToOutbound) {
    this.packagesToOutbound = packagesToOutbound;
  }

  public OutboundOrderCreationData productsToOutbound(List<ProductQuantity> productsToOutbound) {
    this.productsToOutbound = productsToOutbound;
    return this;
  }

  public OutboundOrderCreationData addProductsToOutboundItem(ProductQuantity productsToOutboundItem) {
    if (this.productsToOutbound == null) {
      this.productsToOutbound = new ArrayList<ProductQuantity>();
    }
    this.productsToOutbound.add(productsToOutboundItem);
    return this;
  }

   /**
   * List of product units to be outbound.
   * @return productsToOutbound
  **/
  @Schema(example = "[{\"sku\":\"TestSKU\",\"quantity\":1}]", description = "List of product units to be outbound.")
  public List<ProductQuantity> getProductsToOutbound() {
    return productsToOutbound;
  }

  public void setProductsToOutbound(List<ProductQuantity> productsToOutbound) {
    this.productsToOutbound = productsToOutbound;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OutboundOrderCreationData outboundOrderCreationData = (OutboundOrderCreationData) o;
    return Objects.equals(this.orderPreferences, outboundOrderCreationData.orderPreferences) &&
        Objects.equals(this.packagesToOutbound, outboundOrderCreationData.packagesToOutbound) &&
        Objects.equals(this.productsToOutbound, outboundOrderCreationData.productsToOutbound);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderPreferences, packagesToOutbound, productsToOutbound);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OutboundOrderCreationData {\n");
    
    sb.append("    orderPreferences: ").append(toIndentedString(orderPreferences)).append("\n");
    sb.append("    packagesToOutbound: ").append(toIndentedString(packagesToOutbound)).append("\n");
    sb.append("    productsToOutbound: ").append(toIndentedString(productsToOutbound)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
