/*
 * Selling Partner API for Uploads
 * The Uploads API lets you upload files that you can programmatically access using other Selling Partner APIs, such as the A+ Content API and the Messaging API.
 *
 * OpenAPI spec version: 2020-11-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.amazon.SellingPartnerAPI.api.uploads.v2020_11_01;

import com.amazon.SellingPartnerAPI.ApiResponse;
import com.amazon.SellingPartnerAPI.api.commons.ApiTest;
import com.amazon.SellingPartnerAPI.models.uploads.v2020_11_01.CreateUploadDestinationResponse;
import org.junit.jupiter.api.Test;

import java.util.*;

import static org.junit.jupiter.api.Assertions.*;

public class UploadsApiTest extends ApiTest {

private final UploadsApi api = new UploadsApi.Builder()
    .lwaAuthorizationCredentials(credentials)
    .endpoint(endpoint)
    .build();

    @Test
    public void createUploadDestinationForResourceTest() throws Exception {
        instructBackendMock("createUploadDestinationForResource", "201");
        List<String> marketplaceIds = new ArrayList<>();String contentMD5 = "";String resource = "";

        ApiResponse<CreateUploadDestinationResponse> response = api.createUploadDestinationForResourceWithHttpInfo(marketplaceIds, contentMD5, resource, null);

        assertEquals(201, response.getStatusCode());
        if(201 != 204) assertNotNull(response.getData());
    }

}