/*
 * The Selling Partner API for Sellers
 * The Selling Partner API for Sellers lets you retrieve information on behalf of sellers about their seller account, such as the marketplaces they participate in. Along with listing the marketplaces that a seller can sell in, the API also provides additional information about the marketplace such as the default language and the default currency. The API also provides seller-specific information such as whether the seller has suspended listings in that marketplace.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.amazon.SellingPartnerAPI.api.sellers.v1;

import com.amazon.SellingPartnerAPI.ApiResponse;
import com.amazon.SellingPartnerAPI.api.commons.ApiTest;
import com.amazon.SellingPartnerAPI.models.sellers.v1.GetAccountResponse;
import com.amazon.SellingPartnerAPI.models.sellers.v1.GetMarketplaceParticipationsResponse;
import org.junit.jupiter.api.Test;

import java.util.*;

import static org.junit.jupiter.api.Assertions.*;

public class SellersApiTest extends ApiTest {

private final SellersApi api = new SellersApi.Builder()
    .lwaAuthorizationCredentials(credentials)
    .endpoint(endpoint)
    .build();

    @Test
    public void getAccountTest() throws Exception {
        instructBackendMock("getAccount", "200");
        

        ApiResponse<GetAccountResponse> response = api.getAccountWithHttpInfo();

        assertEquals(200, response.getStatusCode());
        if(200 != 204) assertNotNull(response.getData());
    }

    @Test
    public void getMarketplaceParticipationsTest() throws Exception {
        instructBackendMock("getMarketplaceParticipations", "200");
        

        ApiResponse<GetMarketplaceParticipationsResponse> response = api.getMarketplaceParticipationsWithHttpInfo();

        assertEquals(200, response.getStatusCode());
        if(200 != 204) assertNotNull(response.getData());
    }

}