/*
 * Amazon Shipping API
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * OpenAPI spec version: v2
 * Contact: swa-api-core@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package software.amazon.spapi.models.shipping.v2;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import software.amazon.spapi.models.shipping.v2.ActiveAccounts;
/**
 * The Response  for the GetCarrierAccountsResponse operation.
 */
@Schema(description = "The Response  for the GetCarrierAccountsResponse operation.")


public class GetCarrierAccountsResponse {
  @SerializedName("activeAccounts")
  private ActiveAccounts activeAccounts = null;

  public GetCarrierAccountsResponse activeAccounts(ActiveAccounts activeAccounts) {
    this.activeAccounts = activeAccounts;
    return this;
  }

   /**
   * Get activeAccounts
   * @return activeAccounts
  **/
  @Schema(required = true, description = "")
  public ActiveAccounts getActiveAccounts() {
    return activeAccounts;
  }

  public void setActiveAccounts(ActiveAccounts activeAccounts) {
    this.activeAccounts = activeAccounts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCarrierAccountsResponse getCarrierAccountsResponse = (GetCarrierAccountsResponse) o;
    return Objects.equals(this.activeAccounts, getCarrierAccountsResponse.activeAccounts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(activeAccounts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCarrierAccountsResponse {\n");
    
    sb.append("    activeAccounts: ").append(toIndentedString(activeAccounts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
