/*
 * Selling Partner API for Replenishment
 * The Selling Partner API for Replenishment (Replenishment API) provides programmatic access to replenishment program metrics and offers. These programs provide recurring delivery of any replenishable item at a frequency chosen by the customer.  The Replenishment API is available worldwide wherever Amazon Subscribe & Save is available or is supported. The API is available to vendors and FBA selling partners.
 *
 * OpenAPI spec version: 2022-11-07
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.amazon.SellingPartnerAPI.api.replenishment.v2022_11_07;

import com.amazon.SellingPartnerAPI.ApiResponse;
import com.amazon.SellingPartnerAPI.api.commons.ApiTest;
import com.amazon.SellingPartnerAPI.models.replenishment.v2022_11_07.ErrorList;
import com.amazon.SellingPartnerAPI.models.replenishment.v2022_11_07.GetSellingPartnerMetricsRequest;
import com.amazon.SellingPartnerAPI.models.replenishment.v2022_11_07.GetSellingPartnerMetricsResponse;
import org.junit.jupiter.api.Test;

import java.util.*;

import static org.junit.jupiter.api.Assertions.*;

public class SellingpartnersApiTest extends ApiTest {

private final SellingpartnersApi api = new SellingpartnersApi.Builder()
    .lwaAuthorizationCredentials(credentials)
    .endpoint(endpoint)
    .build();

    @Test
    public void getSellingPartnerMetricsTest() throws Exception {
        instructBackendMock("getSellingPartnerMetrics", "200");
        

        ApiResponse<GetSellingPartnerMetricsResponse> response = api.getSellingPartnerMetricsWithHttpInfo(null);

        assertEquals(200, response.getStatusCode());
        if(200 != 204) assertNotNull(response.getData());
    }

}