name: Sync PHP SDK to selling-partner-api-php-release

on:
  push:
    paths:
      - "php/sdk/**"
    branches:
      - main
  workflow_dispatch:
    inputs:
      newVersionNumber:
        type: string
        description: New version number
        required: true

env:
  SDK_VERSION: ${{ github.event.inputs.newVersionNumber }}

concurrency:
  group: sync-php-sdk-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repository (selling-partner-api-sdk)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
          path: selling-partner-api-sdk

      - name: Clone Target Repository (selling-partner-api-php-release)
        run: |
          mkdir -p ~/workspace
          cd ~/workspace
          echo "Cloning selling-partner-api-php-release..."
          git clone --depth=1 https://x-access-token:${{ secrets.TOMLIKED_PAT }}@github.com/amzn/selling-partner-api-php-release.git target-repo || { echo "Git clone failed"; exit 1; }

      - name: Create a Release Tag
        run: |
          cd ~/workspace/target-repo
          git fetch origin main
          git checkout main
          TAG_NAME="${{ env.SDK_VERSION }}"
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.TOMLIKED_PAT }}

      - name: Publish GitHub Release
        run: |
          gh release create "${{ env.TAG_NAME }}" \
            --title "SDK Release ${{ env.SDK_VERSION }}" \
            --notes "This release includes the latest sync from \`selling-partner-api-sdk/php/sdk/\`."
        env:
          GH_TOKEN: ${{ secrets.TOMLIKED_PAT }}
      
