name: Sync PHP SDK to selling-partner-api-php-release

on:
  push:
    paths:
      - "php/sdk/**"
    branches:
      - main
  workflow_dispatch:
    inputs:
      newVersionNumber:
        type: string
        description: New version number
        required: true

env:
  SDK_VERSION: ${{ github.event.inputs.newVersionNumber }}

concurrency:
  group: sync-php-sdk-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Target Repository
        run: |
          mkdir -p ~/workspace
          cd ~/workspace
          echo "Cloning selling-partner-api-php-release..."
          git clone --depth=1 https://x-access-token:${{ secrets.TOMLIKED_PAT }}@github.com/amzn/selling-partner-api-php-release.git target-repo || { echo "Git clone failed"; exit 1; }

      - name: Debug Check target-repo
        run: |
          echo "Checking if target-repo exists..."
          ls -la ${HOME}/workspace/
          if [ ! -d "${HOME}/workspace/target-repo" ]; then
            echo "ERROR: target-repo does not exist!"
            exit 1
          fi
          ls -la ${HOME}/workspace/target-repo
          ls -la ${HOME}/workspace/target-repo/.git || { echo "ERROR: .git directory is missing!"; exit 1; }

      - name: Sync 'php/sdk/' to Target Repo
        run: |
          rsync -av --delete php/sdk/ ~/workspace/target-repo/

      - name: Commit and Push Changes
        run: |
          cd ~/workspace/target-repo
          git config user.email "tomliked@amazon.co.jp"
          git config user.name "tomliked"
          BRANCH_NAME="sync-sdk-${{ env.SDK_VERSION }}-$(date +%Y%m%d-%H%M%S)"
          git checkout -b "$BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          
          git add -A
          git commit -m "Sync PHP SDK - Version ${{ env.SDK_VERSION }}" || echo "No changes to commit"
          git push origin "$BRANCH_NAME"

      - name: Create a Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.TOMLIKED_PAT }}
          branch: ${{ env.BRANCH_NAME }}
          base: main
          title: "Sync PHP SDK - Version ${{ github.event.inputs.newVersionNumber }}"
          body: |
            This PR syncs the latest changes from `selling-partner-api-sdk/php/sdk/` to `selling-partner-api-php-release/`.
            - Version: ${{ github.event.inputs.newVersionNumber }}
          labels: automated, sdk-sync
